### ISSUE TITLE
@service isn't working in apps that have this addon installed

### ISSUE THREAD

**Issue by pzuraq** [rwjblue/ember-holy-futuristic-template-namespacing-batman#226] opened 2019-09-24 23:30 UTC
In modern Ember app's you can define services without parameters:

```js
class Foo {
  @service bar; 
}
```

The patch this addon includes breaks this somehow.

**Comment by asakusuma** [comment] 2019-12-03 20:33
I'm running into the same issue. I am trying to inject a service onto a modifier. Works fine if I do `@service('blah') blah;`. Breaks if I do `@service blah`. 

This line breaks:
https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/blob/00f7520da09a10ef16ddcf4e45858bc3e3e1a8ec/vendor/service-inject-3.js#L11

`name` is a `ClassBasedModifier` when it fails. I'm assuming the problem is that the caller is passing in something other than a string. The caller is `_applyDecoratedDescriptor`, which appears to be a babel thing.

**Comment by asakusuma** [comment] 2019-12-03 20:33
The error I get is: `Uncaught (in promise) TypeError: name.replace is not a function`

**Comment by rwjblue** [comment] 2019-12-04 23:39
There is an open PR to address this, but needs some tweaks last I looked.

**Comment by rwjblue** [comment] 2019-12-04 23:39
https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/pull/245

**Comment by rwjblue** [comment] 2019-12-17 17:52
Fixed in #245

**Closed by rwjblue** 2019-12-17 17:52 UTC
